import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {TooltipProvider} from "@components/ui/tooltip";
import {Toaster} from "@components/ui/toaster";
import { Toaster as Sonner } from "@components/ui/sonner";
// import {QueryClient, QueryClientProvider} from "@tanstack/react-query";
import React from "react";
import Navbar from "@components/layout/Navbar";
import Footer from "@components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const queryClient = new QueryClient();

  return (
      <html>
        {/*<QueryClientProvider client={queryClient}>*/}
          <TooltipProvider>
              <body
                  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
              >
              <Toaster/>
              <Sonner/>

              <div className="flex flex-col min-h-screen">
                  <Navbar/>

                  <main className="flex-grow pt-16">
                      {children}
                  </main>

                  <Footer/>
              </div>
              </body>
          </TooltipProvider>
          {/*</QueryClientProvider>*/}
      </html>
  );
}
