version: "3.8"

services:

  carzup-blog-watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    environment:
      - REPO_USER=${GITHUB_USER}
      - REPO_PASS=${GITHUB_PAT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # PostgreSQL Database for Laravel API
  carzup-blog-db:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - carzup_blog_network

  # Laravel API Service
  carzup-blog-backend:
    image: ghcr.io/carzup/carzupblog/carzupblog_api:main
    container_name: carzup_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: http://localhost:4389
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "4389:4389"
    depends_on:
      - carzup-blog-db
    networks:
      - carzup_blog_network

  # Next.js Frontend Service
  carzup-blog-frontend:
    image: ghcr.io/carzup/carzupblog/carzupblog_frontend:main
    container_name: carzup_frontend
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "3000:3000"
    depends_on:
      - carzup-blog-backend
    networks:
      - carzup_blog_network

networks:
  carzup_blog_network:
    driver: bridge

volumes:
  db_data: