name: Build and publish frontend Docker image

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: CarzUp/CarzUpBlog/carzup_blog_frontend

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Extract metadata (tags, labels) for Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend  # Path to the frontend Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
